### PR TITLE
ENH add option to ignore warnings

### PR DESCRIPTION
**Pull request by glemaitre**
Add option to ignore warning when running `ramp test`

It is useful for: https://github.com/paris-saclay-cds/ramp-board/pull/362

### CODE REVIEW

**Comment by glemaitre** [comment]
ping @agramfort 

I think it can be merged.

**Comment by agramfort** [comment]
travis complains

**Comment by glemaitre** [comment]
Does not look related. I would relaunch Travis.

**Comment by agramfort** [comment]
still red :(

>

**Comment by glemaitre** [comment]
Uhm this is passing now. I am almost sure this is a random bug because of my change as nothing to do with the kit itself.

**Comment by agramfort** [comment]
thx @glemaitre !

**Pull request merged**
