### PR TITLE
FIX: Unicode issues

### LINKED ISSUE #115: Encoding error in `ramp_test_submission`
I just received a feedback from a user

```
[rhlozek@midway-login2 supernovae]$ ~/.local/bin/ramp_test_submission --quick-test
Testing PLAsTiCC transient classification RAMP
Reading train and test files from ./data ...
Reading cv ...
Training ./submissions/starting_kit ...
CV fold 0
score   auc   acc   nll
train  1.00  1.00  0.11
valid  0.85  0.75  0.47
test   0.74  0.59  0.89

CV fold 1
score   auc   acc   nll
train  1.00  1.00  0.12
valid  0.86  0.75  0.46
test   0.79  0.68  0.65

CV fold 2
score   auc   acc   nll
train  1.00  0.99  0.12
valid  0.85  0.78  0.47
test   0.80  0.61  1.40

----------------------------
Mean CV scores
----------------------------

Traceback (most recent call last):
  File "/home/rhlozek/.local/bin/ramp_test_submission", line 11, in <module>
    load_entry_point('ramp-workflow==0.2.0+23.g7a4b7e0', 'console_scripts', 'ramp_test_submission')()
  File "/home/rhlozek/.local/lib/python3.5/site-packages/rampwf/utils/command_line.py", line 85, in ramp_test_submission
    retrain=retrain)
  File "/home/rhlozek/.local/lib/python3.5/site-packages/rampwf/utils/testing.py", line 582, in assert_submission
    _print_df_scores(df_mean_scores, score_types, indent='\t')
  File "/home/rhlozek/.local/lib/python3.5/site-packages/rampwf/utils/testing.py", line 262, in _print_df_scores
    print('\n'.join(df_repr_out))
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 118: ordinal not in range(128)
```

@glemaitre @jorisvandenbossche any idea ?

I just asked for the OS name and version.

### PR DESCRIPTION
**Pull request by aboucaud**
This is an attempt to fix #115 by removing any occurence of the
str() method to cast variables into string and replacing them with
string formatting.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I don't understand how this can ever solve an issue on Python 3. Both str(..) or "..".format(..) return unicode. 
Note also that the error happens when printing it, not before when constructing the string.

**Comment by aboucaud** [comment]
So shall I `.encode('utf-8')` before printing in all printing methods ?

**Comment by aboucaud** [comment]
I have no idea how to write a test for this..

**Comment by aboucaud** [comment]
Closed after #115 was fixed

**Pull request closed without merging**
