### PR TITLE
FIX failing test

### PR DESCRIPTION
**Pull request by lucyleeow**
#205

### CODE REVIEW

**Comment by lucyleeow** [comment]
Looking at the tensorflow system requirements, it seems a newer version of pip is require than what we are using:

```
$ pip --version

pip 9.0.1 from /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (python 3.6)
```

I'll update the `.travis.yml` file to to update pip, unless there are objections?

**Comment by lucyleeow** [comment]
@agramfort will the underlying problem for the fail on tensorflow > 2.0.0 need to be addressed though?

**Comment by agramfort** [comment]
it's a packaging tensorflow issue I would say.

>

**Comment by lucyleeow** [comment]
I'll merge then.

**Pull request merged**
