### PR TITLE
[MRG + 1] Use versioneer for version management

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
This currently gives:

```
In [1]: import rampwf

In [2]: rampwf.__version__
Out[2]: 'v0.1.0+16.g28f84af'
```

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Note: all those files are automatically generated and should never be adapted by hand (otherwise it would be a lot of code to maintain that this adds ..)

**Comment by kegl** [comment]
Travis fails
```
Processing /home/travis/build/paris-saclay-cds/ramp-workflow
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-gCmmfo-build/setup.py", line 28, in <module>
        VERSION = version
    NameError: name 'version' is not defined
```
otherwise LGTM.

**Comment by jorisvandenbossche** [comment]
Whoops, fixed that

**Comment by glemaitre** [comment]
LGTM

**Pull request merged**
