### PR TITLE
Improve pickle

### PR DESCRIPTION
**Pull request by albertcthomas**
Pickling was working but raising a non related warning because the file was not read as a binary file. An error should have been raised instead of a warning saying that the model cannot be pickled.

The pickled file is now read as a binary file and only Pickle errors are caught by the try except clause.

PS: this is also fixing two non related flake8 errors to make Travis happy

### CODE REVIEW

**Comment by agramfort** [comment]
any chance you can add a test?

**Comment by albertcthomas** [comment]
I will try to add a test. I also need to double check the errors generated when unpickling as you can have other errors than a PickleError (see [pickle doc](https://docs.python.org/3/library/pickle.html#pickle.UnpicklingError))

**Comment by albertcthomas** [comment]
1. I don't know if it is possible to have a test for the original fix, replacing 'r' with 'rb' as pickle.load can raise any exception and not just Unpickling errors.

2. We can still have a test checking that if we cannot pickle then the warning message is raised.

3. With the last commit, if the trained workflow cannot be dumped we don't even try to load it, we print the warning and return the trained workflow. If it can be dumped we try to load it. The only drawback with this is that it might overcomplicate the code. Let me know what you think.

Are we sure that the load part is useful? Is it possible to have an error when loading a pickled object just after dumping it? Here we try to load it in the same module that was used to dump it, within the same python session/process. In my opinion troubles can come when trying to load a pickled object in a different session (e.g. a different python process where modules have to be imported) or with a different python version. I don't know enough about pickle for this :).

**Comment by agramfort** [comment]
good to go from your end?

next time do not open a PR from the upstream repo. thx

**Comment by albertcthomas** [comment]
I just rebased. If tests pass, good to go for me.

Ok for the PR from the upstream repo.

**Comment by agramfort** [comment]
thx @albertcthomas

**Pull request merged**
