### PR TITLE
[WIP] testing backend submission

### PR DESCRIPTION
**Pull request by glemaitre**

### CODE REVIEW

**Comment by agramfort** [comment]
@kegl review time :)

**Comment by kegl** [comment]
Let's deal with this after the zip encrypting is solved.

**Comment by kegl** [comment]
I think I merged too fast. I don't see /bins/test_submission

**Comment by jorisvandenbossche** [comment]
Usually we use the convention that "WIP" in the title means it is work in progress and should not yet be merged (but you eg already want to test it or that other people can look at it)

**Pull request merged**
