### PR TITLE
Epidemium

### PR DESCRIPTION
**Pull request by kegl**

### CODE REVIEW

**Comment by kegl** [comment]
Can we merge this?

**Comment by jorisvandenbossche** [comment]
What is the `n_colunms` about?

**Comment by kegl** [comment]
n_columns is the number of columns of the output y_pred (or y_true). I do this assert because submitters (RAMP participants) can return whatever they want in their last predict(), and I want to throw an error early error if the format of their y_pred is illegal.

**Comment by jorisvandenbossche** [comment]
Ah, OK, that makes sense. We only should then give a more informative error message to the user.

**Comment by kegl** [comment]
True. You want to give it a try?

**Comment by jorisvandenbossche** [comment]
Yes, but not today :-)

**Pull request merged**
