### PR TITLE
Partial training

### PR DESCRIPTION
**Pull request by albertcthomas**
On behalf of @kegl 

This PR adds the possibility of partial training to the workflow by loading a previous pickled model
- [x] add command-line option `--partial-train`
- [x] add optional prev_model to train_workflow in classifier, regressor, feature_extractor_classifier, and feature_extractor_regressor
- [x] titanic_old test with partial training
- [x] air_passenger_old test with partial training
- [x] decouple pickling and unpickling
- [x] test pickle_model and unpickle_model
- [x] name change from (un)pickle_model to (un)pickle_trained_workflow to be more precise

### CODE REVIEW

**Comment by kegl** [comment]
Ping @agramfort and @rth , if someone would like to review from the Saclay side. It went through internal review on ours, @albertcthomas will comment tomorrow. The two reasons we decided to do this:
1. We want to do warm start in hyperopt.
2. We are partially training the system models in our rl_simulator application (generative_models branch).
But it can also be used from the command line if someone wants to train, the stop and check the errors, then start from the partially trained model. Especially in the development phase it could be handy.

**Comment by albertcthomas** [comment]
Travis is missing because of the migration from travis-ci.org to travis-ci.com. I don't think I have the rights to add the repo to travis-ci.com.

**Comment by rth** [comment]
Should we just migrate to GH Actions? Those are enabled by default, and the CI is setup is fairly straightforward in this repo.

**Comment by albertcthomas** [comment]
> Should we just migrate to GH Actions? Those are enabled by default, and the CI setup is fairly straightforward in this repo.

This might be better indeed.

**Comment by kegl** [comment]
> Should we just migrate to GH Actions? Those are enabled by default, and the CI setup is fairly straightforward in this repo.
Would be great!

**Comment by rth** [comment]
Could you please merge master in to enable CI?

**Comment by kegl** [comment]
@agramfort if no objections from the Saclay side, we'll merge this next week.

**Pull request merged**
