### PR TITLE
DOC Typos found by codespell

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Add [codespell](https://github.com/codespell-project/codespell) configuration in `setup.cfg`.

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
Should I add a `spellcheck` target to the `Makefile`?

It could even be a **[manual](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages)** pre-commit hook.

**Comment by agramfort** [comment]
+1 for a convenient spellcheck target in makefile

**Comment by DimitriPapadopoulos** [comment]
Added the `spellcheck` target - should it be the more generic `spellcheck` or `codespell`?

**Review by agramfort — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
Ah, I could also add `'spellcheck': ['codespell']` to `EXTRAS_REQUIRE`:
https://github.com/paris-saclay-cds/ramp-workflow/blob/7d075219d42cf5c8cca62c6c9804dba8c04907cc/setup.py#L40-L43

**Comment by rth** [comment]
Thanks @DimitriPapadopoulos . I think the current version is sufficient. Would you be interested in also doing this on the ramp-board repo?

**Comment by rth** [comment]
OK, because GH Actoins were not run here, it actually broke flake8 on master. Will try to fix it soon, unless someone does it before.

**Pull request merged**
