### PR TITLE
Ramp leaderboard

### PR DESCRIPTION
**Pull request by mehdidc**
Add a simple command line "ramp_leaderboard" (https://github.com/mehdidc/ramp-leaderboard) to display a leaderboard of local submissions.
(see #132)

Continuation of #133 using my fork for the source branch

### CODE REVIEW

**Comment by mehdidc** [comment]
I added unit tests.

**Comment by agramfort** [comment]
travis is not happy

**Comment by mehdidc** [comment]
it's because of tabulate, we will need @glemaitre's PR #138 to be merged

**Comment by kegl** [comment]
> travis is not happy

And how's that make you feel, @agramfort? :)

**Comment by glemaitre** [comment]
Travis not happy so is @agramfort :)

**Comment by mehdidc** [comment]
So can we merge this ?

**Comment by kegl** [comment]
Fine or me. Perhaps add a new section to the wiki. `ramp_blend_submissions` is also something we could document there. cc @aboucaud

**Comment by mehdidc** [comment]
Done for the wiki.

**Pull request merged**
