### PR TITLE
Advanced

### PR DESCRIPTION
**Pull request by kegl**
This is an open PR to see the status of the `advanced` branch wrt `master`. The CDS team @agramfort @glemaitre decides if it is merged.

Additions compared to `master`:
- [x] Decoupled CV #243 
- [x] `--data-label` option to specify a dataset when running `ramp-test` #245 
- [x] fixing ramp-leaderboard (including fix for `--bagged` and `--data-label` option) #247 
- [x] adding an option to `ramp-blend` to select the `--score_metrics_index` to blend on #247

### CODE REVIEW

**Comment by kegl** [comment]
I'd be favorable to merge this (and the corresponding branch on ramp-board) into master  after the data camp season. We have now a second server running the advanced branch seamlessly, with one challenge finished. We also have a protocol put in place for testing both workflow and board before merging anything into workflow (not automatic but easy to follow): https://github.com/paris-saclay-cds/ramp-workflow/tree/advanced#testing-ramp-board

The advantage would be to unify our workforces for maintenance and development.

@agramfort was the main opponent to this, I'll let you decide.

**Comment by agramfort** [comment]
yes datacamp season is over. server should be quiet for the next 3-4 weeks.

@rth can you take care of this? merge, make a release and update the prod server?

**Comment by agramfort** [comment]
note that this cannot be merged as is as it refers to instructions that need to be adjusted once this is merged

**Comment by kegl** [comment]
@agramfort , can you elaborate? You mean the testing instructions here https://github.com/paris-saclay-cds/ramp-workflow/tree/advanced#testing-ramp-board? What's your suggestion, would you like to first PR the README?

The issue is that we're close to launching the permanent Huawei site, where there will be development the make the site more pro (accessibility, GDPR), which may also be interesting for ramp.studio. It would be useful to merge the two branches before that.

**Comment by rth** [comment]
I think Alex meant that say `doc/index.rst` currently specifies to install this branch (and some CI changes) that would need to be updated before merging (and possibly other updated parts of the doc).

> merge, make a release and update the prod server?

Yes, I can help with that next week. It would indeed be great to keep a common code base.

**Comment by kegl** [comment]
OK yes, got it :), thx @rth

**Comment by rth** [comment]
So all changes from this branch were merged as separate PRs into master, so I'm going to close this PR.

**Comment by albertcthomas** [comment]
Thanks a lot @rth

**Pull request closed without merging**
