### PR TITLE
save fold scores

### PR DESCRIPTION
**Pull request by mehdidc**
Save the scores of each fold into a csv. I would find that useful when experimenting  with ramp_test_submission locally. Like I am thinking to have a minimal tool that displays the leaderboard based on all submissions in submission/.

### CODE REVIEW

**Comment by kegl** [comment]
I like this, anybody has an objection?

**Comment by agramfort** [comment]
not me

**Comment by mehdidc** [comment]
Here is the tool if you want to take I look: https://github.com/mehdidc/ramp-leaderboard

**Comment by kegl** [comment]
I like the additional tool, can you add it to rampwf and document it in the wiki?

**Pull request merged**
