### PR TITLE
Autocompletion for submission names

### PR DESCRIPTION
**Pull request by albertcthomas**
If this can be useful to anyone I am sharing this here.

This was done following [click documentation](https://click.palletsprojects.com/en/7.x/bashcomplete/#shell-completion).

As written in the [documentation](https://click.palletsprojects.com/en/7.x/bashcomplete/#activation) I need to activate the autocompletion for my shell for this to work.

### CODE REVIEW

**Comment by kegl** [comment]
Amazing, thanks!

Could also be done for the data label, examining folders in ./data

@agramfort do you or someone from Saclay wants to approve it?

**Review by rth — COMMENTED** [review]
This looks nice indeed!

Could you please add,
>  I need to activate the autocompletion for my shell for this to work.

somewhere in the ramp-workflow documentation?

**Comment by albertcthomas** [comment]
> Could also be done for the data label, examining folders in ./data

Yes in the advanced branch.

**Comment by albertcthomas** [comment]
> Could you please add,
> 
> > I need to activate the autocompletion for my shell for this to work.
> 
> somewhere in the ramp-workflow documentation?

Yes, this could also benefit from some tests, if not the full autocompletion thing, which can be hard to test, maybe the function itself.

**Comment by albertcthomas** [comment]
I also tried something using the `args` argument of the `get_submissions` function so that we could look if `ramp-submission-dir` is specified and look into this directory. However I don't really know this path is specified in the command line and trying it lead to several errors that I did not want to deal with to not make a function hard to test too complicated. Besides is there a real use of this option besides on the server running the submissions submitted by the users and in the tests where no autocompletion is needed? It seems I would prefer telling the users to call `ramp-test` in the root dir where they have the `problem.py` and the `submissions` folder. Anyway this is maybe going out of the scope of this PR :)

**Comment by agramfort** [comment]
LGTM 

+1 for merge if CIs are green

**Comment by albertcthomas** [comment]
> > Could you please add,
> > > I need to activate the autocompletion for my shell for this to work.
> > 
> > 
> > somewhere in the ramp-workflow documentation?
> 
> Yes, this could also benefit from some tests, if not the full autocompletion thing, which can be hard to test, maybe the function itself.

Actually, `ramp-test` is not in the documentation, only `ramp_test_submission` which does not use `click`...

**Comment by agramfort** [comment]
do you have a minute to update the doc? thx

no objection to merge here

**Comment by albertcthomas** [comment]
> do you have a minute to update the doc? thx

I am not sure what the plan is here. Should we just replace `ramp_test_submission` by `ramp-test`? Add a `ramp-test` entry? What was the reason to keep both? Backward compatibility?

**Comment by agramfort** [comment]
I would just document ramp-test now. ramp_test_submission should ideally be
deprecated

>

**Comment by albertcthomas** [comment]
I’ll document `ramp-test` and leave the rest for another PR

**Comment by albertcthomas** [comment]
`ramp-test` was in fact already in the master doc (but not in the doc of the last release).

**Comment by kegl** [comment]
I took care of this already, the old cli is deleted from the advanced branch:
https://github.com/paris-saclay-cds/ramp-workflow/blob/advanced/setup.py
https://paris-saclay-cds.github.io/ramp-docs/ramp-workflow/advanced/command_line.html

We should merge it into master.

**Comment by albertcthomas** [comment]
It's already in master (https://github.com/paris-saclay-cds/ramp-workflow/blob/master/doc/command_line.rst). I got confused for not looking at the correct version: the documentation website shows the documentation of the last stable release (0.3.3), not the one of master (0.4).

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
Thx @albertcthomas

**Comment by albertcthomas** [comment]
Thanks for the reviews and comments :)

**Pull request merged**
